#app/config/routing.yml
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

#app/config/routing.yml
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#app/config/routing.yml
user_bundle:
   resource: "@UserBundle/Resources/config/routing.yml"
